# Generated by Django 3.2.15 on 2022-08-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decomposition',
            new_name='description',
        ),
    ]
